---

# Run with commands: 
# ansible-playbook -i inventory snmp-config-04.yml -v
# ansible-playbook -i inventory snmp-config-04.yml --check
# ansible-playbook -i inventory snmp-config-04.yml --check -v
# ansible-playbook -i inventory snmp-config-04.yml -v

- name: PLAY 1 - DEPLOYING SNMP CONFIGURATIONS ON IOS
  hosts: ios
  connection: ansible.netcommon.network_cli
  gather_facts: false

  tasks:

    - name: TASK 1 IN PLAY 1 - ENSURE SNMP COMMANDS EXIST ON IOS DEVICES
      cisco.ios.ios_config:
        commands:
          - snmp-server community ntc-course RO
          - snmp-server community supersecret RW
          - snmp-server location NYC_HQ_COLO
          - snmp-server contact JOHN_SMITH

- name: PLAY 2 - DEPLOYING SNMP CONFIGURATIONS ON JUNOS
  hosts: vmx
  connection: ansible.netcommon.netconf
  gather_facts: false

  tasks:

    - name: TASK 1 IN PLAY 2 - ENSURE SNMP COMMANDS EXIST ON JUNOS DEVICES
      junipernetworks.junos.junos_config:
        lines:
          - set snmp community public authorization read-only
          - set snmp community supersecret authorization read-write
          - set snmp location NYC_HQ_COLO
          - set snmp contact JOHN_SMITH