# Task 1
# - name: USING THE DEBUG MODULE
#   hosts: ios
#   connection: local
#   gather_facts: false

# Commands:
# ansible-playbook -i inventory_2 pb_debug.yml

# Task 1-5
# - name: USING THE DEBUG MODULE
#   hosts: all
#   connection: local
#   gather_facts: false

# Commands:
# ansible-playbook -i inventory_3 pb_debug.yml

# Task 3-3
# Commands:
# ansible-playbook -i inventory_4 pb_debug.yml

# Task 5-2
# Commands:
# ansible-playbook -i inventory_5 pb_debug.yml

---

- name: USING THE DEBUG MODULE
  hosts: csr1
  connection: local
  gather_facts: false


  tasks:
    - name: DEBUG AND PRINT TO TERMINAL
      ansible.builtin.debug:
        var: ntc_vendor

    - name: DEBUG AND PRINT DEVICE TYPE TO TERMINAL
      ansible.builtin.debug:
        var: ntc_device_type

    - name: DEBUG AND PRINT THE OS
      ansible.builtin.debug:
        msg: "The OS for {{ inventory_hostname }} is {{ ansible_network_os }}."

    - name: DEBUG AND PRINT INVENTORY_HOSTNAME VS ANSIBLE_HOST
      ansible.builtin.debug:
        msg: "Devices defined in inventory_hostname: {{ inventory_hostname }} and ansible_host: {{ ansible_host }}"

    - name: DEBUG AND PRINT GROUP_NAMES
      ansible.builtin.debug:
        var: group_names

    - name: DEBUG AND PRINT GROUPS
      ansible.builtin.debug:
        var: groups

    - name: DEBUG AND PRINT ANSIBLE_VERSION
      ansible.builtin.debug:
        msg: "Ansible Version: '{{ ansible_version }}'"