---

- name: TEST REACHABILITY
  hosts: ios
  connection: ansible.netcommon.network_cli
  gather_facts: false

  vars:
    target_ips:
      - "10.0.0.15"
      - "10.0.0.2"
      - "198.6.1.4"

  tasks:

  - name: CREATE PING-RESPONSES DIRECTORY FOR RESULTS
    ansible.builtin.file:
      path: ./ping-responses/
      state: directory

  - name: RUN TEST PING COMMAND
    cisco.ios.ios_command:
      commands: "ping {{ item }} repeat 2"
    register: ping_results
    loop: "{{ target_ips }}"

  - name: VERIFY REGISTERED VARIABLE
    ansible.builtin.debug:
      var: ping_results

  - name: TEST LOOPING OVER REGISTERED VARIABLE
    ansible.builtin.debug:
      var: "{{ item }}"
    loop: "{{ ping_results.results }}"

  - name: GENERATE PING RESULT
    ansible.builtin.template:
      src: basic-copy-single.j2
      dest: "./ping-responses/ping_results_from_{{ inventory_hostname }}.txt"

